version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch-8:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server
    volumes:
      - ./data/redis:/data:delegated
    env_file:
      - ".env"
    ports:
      - "6379:6379"
